apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: member-v2-ingress
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: test3-subdomain.domain.com
spec:
  rules:
    - host: test3-subdomain.domain.com # just testing garbage for the overlay
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: member-v2
                port:
                  number: 80