namespace: dash-test3 # this determines the namespace for the application for test3
resources:
  - ../../base
patches:
# This patch is used to add the ingress for the application - mainly test3 DNS via external DNS, etc
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: member-v2-ingress
